version: "3.3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contact_book
    ports:
      - "5432:5432"